### ISSUE TITLE
EC2 ami is no longer available

### ISSUE THREAD

**Issue by d1h** [fluo-io/fluo#615]
The m3.large ami-61bbf104 instance is us-east is no longer available.
This is referenced in util.py at line 71.

**Comment by keith-turner** [comment]
I was able to launch a cluster using ami-61bbf104, however when I search for that AMI in the EC2 console I can not find it.  That made me scratch my head.   Starting at the following page and poking around, I was able to determine the problem.

https://aws.amazon.com/marketplace/pp/B00O7WM7QW

The image ami-61bbf104 is deprecated and no longer available for new customers.  So I guess since I used it before, its still available to me.   The latest centos 7 image is ami-6d1c2007, we need to update to that in the scripts.  

I wonder if there is a programatic way to get the latest centos7 ami using the AWS marketpalce ID for centos 7.

**Comment by keith-turner** [comment]
Closing this issue as I opened a fluo-deploy issue.
